[[files]]
source = "/home/thor/obsidian/writing/blog/Solving ZK Hack IV puzzle 1.md"

[[files]]
source = "/home/thor/obsidian/writing/blog/I'm looking for a job.md"

[[files]]
source = "../../obsidian/writing/blog/Getting Started with Obsidian.md"

[[files]]
source = "../../obsidian/writing/blog/Getting Started with Obsidian.md"
