complete -c runi -n "__fish_use_subcommand" -s c -l completions -d 'Generate shell completions, using doc strings for subcommand hints' -r -f -a "{bash	'',elvish	'',fish	'',powershell	'',zsh	''}"
complete -c runi -n "__fish_use_subcommand" -s v -l verbose -d 'Set the verbosity. Use -v for DEBUG, -vv for TRACE. None for INFO'
complete -c runi -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c runi -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c runi -n "__fish_use_subcommand" -f -a "superscript"
complete -c runi -n "__fish_use_subcommand" -f -a "subscript"
complete -c runi -n "__fish_use_subcommand" -f -a "script"
complete -c runi -n "__fish_use_subcommand" -f -a "script-bold"
complete -c runi -n "__fish_use_subcommand" -f -a "fullwidth"
complete -c runi -n "__fish_use_subcommand" -f -a "gothic"
complete -c runi -n "__fish_use_subcommand" -f -a "gothic-bold"
complete -c runi -n "__fish_use_subcommand" -f -a "sans"
complete -c runi -n "__fish_use_subcommand" -f -a "sans-italic"
complete -c runi -n "__fish_use_subcommand" -f -a "monospace"
complete -c runi -n "__fish_use_subcommand" -f -a "sans-bold"
complete -c runi -n "__fish_use_subcommand" -f -a "sans-bold-italic"
complete -c runi -n "__fish_use_subcommand" -f -a "serif-bold"
complete -c runi -n "__fish_use_subcommand" -f -a "small-caps"
complete -c runi -n "__fish_use_subcommand" -f -a "circled"
complete -c runi -n "__fish_use_subcommand" -f -a "circled-negative"
complete -c runi -n "__fish_use_subcommand" -f -a "squared"
complete -c runi -n "__fish_use_subcommand" -f -a "squared-negative"
complete -c runi -n "__fish_use_subcommand" -f -a "double-struck"
complete -c runi -n "__fish_use_subcommand" -f -a "inverted"
complete -c runi -n "__fish_use_subcommand" -f -a "reversed"
complete -c runi -n "__fish_use_subcommand" -f -a "faux-cyrillic"
complete -c runi -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c runi -n "__fish_seen_subcommand_from superscript" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from superscript" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from subscript" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from subscript" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from script" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from script" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from script-bold" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from script-bold" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from fullwidth" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from fullwidth" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from gothic" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from gothic" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from gothic-bold" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from gothic-bold" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from sans" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from sans" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from sans-italic" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from sans-italic" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from monospace" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from monospace" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from sans-bold" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from sans-bold" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from sans-bold-italic" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from sans-bold-italic" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from serif-bold" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from serif-bold" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from small-caps" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from small-caps" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from circled" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from circled" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from circled-negative" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from circled-negative" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from squared" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from squared" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from squared-negative" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from squared-negative" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from double-struck" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from double-struck" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from inverted" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from inverted" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from reversed" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from reversed" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from faux-cyrillic" -s h -l help -d 'Print help'
complete -c runi -n "__fish_seen_subcommand_from faux-cyrillic" -s V -l version -d 'Print version'
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "superscript"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "subscript"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "script"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "script-bold"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "fullwidth"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "gothic"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "gothic-bold"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "sans"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "sans-italic"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "monospace"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "sans-bold"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "sans-bold-italic"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "serif-bold"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "small-caps"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "circled"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "circled-negative"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "squared"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "squared-negative"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "double-struck"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "inverted"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "reversed"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "faux-cyrillic"
complete -c runi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from superscript; and not __fish_seen_subcommand_from subscript; and not __fish_seen_subcommand_from script; and not __fish_seen_subcommand_from script-bold; and not __fish_seen_subcommand_from fullwidth; and not __fish_seen_subcommand_from gothic; and not __fish_seen_subcommand_from gothic-bold; and not __fish_seen_subcommand_from sans; and not __fish_seen_subcommand_from sans-italic; and not __fish_seen_subcommand_from monospace; and not __fish_seen_subcommand_from sans-bold; and not __fish_seen_subcommand_from sans-bold-italic; and not __fish_seen_subcommand_from serif-bold; and not __fish_seen_subcommand_from small-caps; and not __fish_seen_subcommand_from circled; and not __fish_seen_subcommand_from circled-negative; and not __fish_seen_subcommand_from squared; and not __fish_seen_subcommand_from squared-negative; and not __fish_seen_subcommand_from double-struck; and not __fish_seen_subcommand_from inverted; and not __fish_seen_subcommand_from reversed; and not __fish_seen_subcommand_from faux-cyrillic; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
