// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1668543736);
user_pref("app.update.lastUpdateTime.background-update-timer", 1668543976);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1668543856);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1668543616);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1668544096);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppVersion", "6.0.16");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/thor/snap/zotero-snap/common/Zotero");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\",\"width\":\"240\"},\"zotero-collections-pane\":{},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 6);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"L1\",\"sessionID\":\"6cEDWllO\"}]");
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1668543627);
user_pref("extensions.zotero.sync.server.username", "thorck@protonmail.com");
user_pref("extensions.zotero.useDataDir", true);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1668544372);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1668544372);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1668544372);
